=encoding UTF-8

=head1 NAME

Mojolicious::Plugin::Email - It's a Mojolicious Plugin for sending emails (a work in progress).

=head1 SYNOPSIS

    # register plugin in your application 
    $self->plugin(Email => { 
            from      => '"Administrator" <admin@yourdomain.com>', 
            transport => Email::Sender::Transport::Sendmail->new('/path/to/sendmail'),
    });

    # use it in your controller
    $self->email(
        header => [
            To      => '"Some Name" <some.email@adomain.com>',
            Subject => "Subject",
        ],
        transport => Email::Sender::Transport::SMTP::TLS->new(
            host     => 'smtp_server',
            username => 'username',
            password => 'password',
            port     =>  port,
        ),
        data => [
            template => 'email/template_name',
            info     => 'Some useful data you need in your template'
        ],
        content_type => 'text/html',
        charset      => 'utf8',
        encoding     => '8bit',
        format       => 'email',
    );


    # Your email template "templates/email/template_name.email.ep":
    % layout 'email/default';
    % title 'Subject';

    <p><%= $data->{info} %></p>


    # The default email layout "templates/layouts/email/default.email.ep":
    <html>
        <head><title><%= title %></title></head>
        <body><%= content %></body>
    </html>
    

=head1 VERSION
 
Version 0.03


=head1 AUTHOR

Raul Matei L<mailto:raulmatei@cpan.org>


=head1 COPYRIGHT AND LICENCE

Copyright (C) 2012 by Raul Matei

This program is free software; you can redistribute it and/or modify it under the same terms as Perl itself.

=cut
